title: Adventures of Nomad Mahmud
description: A Tech Nomad's Journey – Web Dev, DevOps & More

url: https://am-mahmud.github.io
# Use baseurl if hosting in a subfolder, leave blank for root domain
baseurl: ""  # Ex: /project-page
paginate_path: "blog/page:num/"
permalink: blog/:title/

# Header Option
# header: large

sass:
  style: compressed

markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
paginate: 5

# Navigation menu
navigation:
  - title: Home
    url: /
  - title: About
    url: /about/
  - title: Blog
    url: /blog/
  - title: Contact
    url: /contact/

# Social links
social:
  github: am-mahmud
  twitter: nomadmahmud
  facebook: nomadmahmud
  email: asif.mahmud@example.com
  linkedin: asif-mahmud
  youtube: NomadMahmudTech
  tumblr: ""

# Google Analytics
google_analytics: "UA-XXXXXXX-X"  # Replace with your own tracking ID

# Disqus comments
disqus:
  shortname: nomadmahmudsite

# Exclude unnecessary files from build
exclude:
  - README.md
  - LICENSE
  - Gemfile
  - Gemfile.lock
