# Site
name: "Adventures of Nomad Mahmud"
title: "Adventures of Nomad Mahmud"
description: "Exploring Web Development, DevOps, and everything tech."
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: ""  # Leave empty for root GitHub Pages
google_analytics: '' # Add GA ID if needed
disqus: 'nomadmahmudsite'
mailchimp-list: ''  # Add your Mailchimp list URL if needed
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  mahmud:
    name: Asif Mahmud
    display_name: Nomad Mahmud
    avatar: 'assets/images/avatar1.jpg'
    email: am.mahmudasif@gmail.com
    web: https://am-mahmud.github.io
    # twitter: https://twitter.com/NomadMahmud
    description: "Hi, I'm Asif Mahmud — documenting my journey as a tech nomad through Web Development, DevOps, and beyond."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Markdown & Syntax
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (Set to "enabled" and add your ad client ID to activate)
adsense: "disabled"
adsense-data-ad-client: ""
adsense-data-ad-slot: ""

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

# Exclude
exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
