title: "Adventures of Nomad Mahmud"
email: am.mahmudasif@gmail.com
timezone: "Asia/Dhaka"
baseurl: ""             # No subdirectory since it's am-mahmud.github.io
permalink: "/:title/"
author: "nomadmahmud"

# Pagination (optional - for future use if needed)
paginate: 10

# Language and Locale
locale: en_us
lang: en_us

# Markdown Setup
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true

# Social Links (optional - edit/remove if not needed)
social:
  facebook: https://facebook.com/yourprofile
  twitter: https://twitter.com/yourprofile
  instagram: https://instagram.com/yourprofile

# Plugins (only the ones GitHub Pages supports)
plugins: 
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Feed
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
