title: "Adventures of Nomad Mahmud"
description: "A journey through tech, DevOps, and web adventures."

# Website URL
url: "https://am-mahmud.github.io"
# Base URL (leave empty if using root domain)
baseurl: "" 

paginate_path: "blog/page:num/"
permalink: blog/:title/

# Header Option
# header: large

sass:
  style: compressed

markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

paginate: 5

# Navigation Links
navigation:
  - title: "Home"
    url: /
  - title: "About"
    url: /about
  - title: "Contact"
    url: /contact
  - title: "Categories"
    url: /categories/

# Social Links
social:
  github: am-mahmud
  # email: am.mahmud.dev@gmail.com
  linkedin: am-mahmud
  # youtube: NomadMahmudYT

# Google Analytics Tracking ID
google_analytics: ""

# Disqus Comments
disqus:
  shortname: nomadmahmudsite
