# Site
name: 'Adventures of Nomad Mahmud'
description: 'A journey to nomad tech'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: '/am-mahmud.github.io'
disqus: 'nomadmahmudsite'
email: 'wowthemesnet@gmail.com'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    sal:
      name:          Asif Mahmud
      site:           https://am-mahmud.github.io
      avatar:         /assets/images/avatar1.jpg
      bio:            "Hi, I am Asif Mahmud, this is my tech nomad adventure diary. I hope you like it!"
      # email:          wowthemesnet@gmail.com

# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: sal
      avatar: /assets/images/avatar1.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]