remote_theme: mmistakes/minimal-mistakes

# Plugins
plugins:
  - jekyll-include-cache
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag

# Site Settings
title: "Adventures of Nomad Mahmud"
url: "https://am-mahmud.github.io"
baseurl: "/am-mahmud.github.io" 

# Pagination
paginate: 5
paginate_path: "/page:num/"

# Theme Skin
minimal_mistakes_skin: "default"

# Navigation Bar
navigation:
  - title: "Home"
    url: /
  - title: "Web Development"
    url: /categories/webdev/
  - title: "DevOps"
    url: /categories/devops/
  - title: "About"
    url: /about/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false

# Custom CSS
sass:
  style: compressed

include:
  - assets/css/custom.css
