# Site Info
name: "Adventures of Nomad Mahmud"
title: "Adventures of Nomad Mahmud"
description: "A journey through Web Development, DevOps, and tech experiments."
logo: "assets/images/logo.png"
favicon: "assets/images/favicon.ico"
baseurl: ""                # Set to "" if using am-mahmud.github.io (root GitHub Pages)
url: "https://am-mahmud.github.io"  # Your GitHub Pages site URL
disqus: "nomadmahmudsite"
email: "am.mahmud@gmail.com"  # Update to your real email
# mailchimp-list: ""         # Add only if you plan to use Mailchimp

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag

# Author Info
authors:
  nomad:
    name: "Asif Mahmud"
    site: "https://am-mahmud.github.io"
    avatar: "/assets/images/avatar1.jpg"
    bio: "Hi, I am Asif Mahmud, a tech nomad sharing my adventures in Web Development, DevOps, and cloud technologies."

# Defaults
defaults:
  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: nomad
      avatar: /assets/images/avatar1.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Pagination
paginate: 10
paginate_path: "/page:num/"

# Exclusions
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
